import { WorkoutPlan } from './types';

export const WORKOUTS: WorkoutPlan[] = [
  {
    id: 'C',
    label: 'Dia C',
    name: 'Perna I — Quadríceps',
    dayOfWeek: 0,
    isRest: false,
    warmup: [
      { text: 'Agachamento sem peso: 2x15 bem lento' },
      { text: 'Afundo no lugar sem peso: 10x cada perna' },
      { text: 'Círculos com o joelho em pé: 10x cada lado' },
      { text: '1 série agachamento com 40% do peso: 10 reps' },
    ],
    exercises: [
      { id: 'C1', name: 'Agachamento Livre com Barra', series: '4x10', rest: '90-120s', initialWeight: '30-40kg total' },
      { id: 'C2', name: 'Leg Press 45', series: '4x12', rest: '90s', initialWeight: '40-60kg' },
      { id: 'C3', name: 'Extensora de Joelho', series: '3x15', rest: '60s', initialWeight: '15-20kg' },
      { id: 'C4', name: 'Afundo com Halteres', series: '3x12', rest: '60-90s', initialWeight: '6-8kg cada' },
      { id: 'C5', name: 'Panturrilha em Pé', series: '4x20', rest: '60s', initialWeight: 'Peso corporal ou 10kg' },
    ],
  },
  {
    id: 'A',
    label: 'Dia A',
    name: 'Peito + Tríceps',
    dayOfWeek: 1,
    isRest: false,
    warmup: [
      { text: 'Rotação de ombro para frente e para trás: 10x cada' },
      { text: 'Abertura de peito com braços: 10 reps lentas' },
      { text: 'Flexão com peso corporal: 2x10 lenta' },
      { text: '1 série de supino com 40% do peso: 12 reps' },
    ],
    exercises: [
      { id: 'A1', name: 'Supino Reto com Barra', series: '4x10', rest: '90-120s', initialWeight: '30-40kg total' },
      { id: 'A2', name: 'Supino Inclinado com Halteres', series: '3x12', rest: '90s', initialWeight: '8-10kg cada (usou 12.5kg)' },
      { id: 'A3', name: 'Crossover no Cabo ou Fly', series: '3x15', rest: '60s', initialWeight: '5-7kg cada lado' },
      { id: 'A4', name: 'Tríceps Pulley Corda', series: '3x15', rest: '60s', initialWeight: '10-15kg (usou 36kg)' },
      { id: 'A5', name: 'Tríceps Testa Skull Crusher', series: '3x12', rest: '60-90s', initialWeight: '10kg total (usou 14kg)' },
    ],
    tip: 'No supino, desça até tocar o peito e empurre explodindo na subida.',
  },
  {
    id: 'REST_TUE',
    label: 'Descanso',
    name: 'Dia de Descanso',
    dayOfWeek: 2,
    isRest: true,
    warmup: [],
    exercises: [],
  },
  {
    id: 'B',
    label: 'Dia B',
    name: 'Costas + Bíceps',
    dayOfWeek: 3,
    isRest: false,
    warmup: [
      { text: 'Rotação de ombros + retração de escápula: 15x' },
      { text: 'Gato-vaca no chão: 10x lentamente' },
      { text: '1 série leve de pulldown com 40% do peso: 12 reps' },
      { text: 'Encolhimento de ombros sem peso: 10x' },
    ],
    exercises: [
      { id: 'B1', name: 'Puxada na Frente Pulldown', series: '4x10', rest: '90s', initialWeight: '30-35kg' },
      { id: 'B2', name: 'Remada Curvada com Barra', series: '4x10', rest: '90-120s', initialWeight: '30kg total (usou 35-40kg)' },
      { id: 'B3', name: 'Remada Serrote Halter Unilateral', series: '3x12', rest: '60s', initialWeight: '10-12kg' },
      { id: 'B4', name: 'Pullover com Halter', series: '3x15', rest: '60s', initialWeight: '8-10kg' },
      { id: 'B5', name: 'Rosca Direta com Barra', series: '3x12', rest: '60s', initialWeight: '15-20kg total' },
      { id: 'B6', name: 'Rosca Concentrada com Halter', series: '3x12', rest: '60s', initialWeight: '6-8kg (usou 7.5kg)' },
    ],
  },
  {
    id: 'D',
    label: 'Dia D',
    name: 'Ombro Completo',
    dayOfWeek: 4,
    isRest: false,
    warmup: [
      { text: 'Rotação de manguito com elástico ou halter 2kg: 2x15 cada lado' },
      { text: 'Encolhimento sem peso: 10x' },
      { text: 'Elevação lateral muito leve (2-3kg): 1x15' },
      { text: 'Círculos com braços estendidos: 10x para frente e para trás' },
    ],
    exercises: [
      { id: 'D1', name: 'Desenvolvimento com Halteres', series: '4x10', rest: '90s', initialWeight: '8-10kg cada' },
      { id: 'D2', name: 'Elevação Lateral com Halteres', series: '4x15', rest: '60s', initialWeight: '4-5kg cada' },
      { id: 'D3', name: 'Elevação Frontal com Halteres', series: '3x12', rest: '60s', initialWeight: '4-5kg cada' },
      { id: 'D4', name: 'Crucifixo Invertido Voador Post.', series: '3x15', rest: '60s', initialWeight: '4-5kg cada' },
      { id: 'D5', name: 'Encolhimento de Ombros', series: '3x15', rest: '60s', initialWeight: '14-16kg cada' },
    ],
  },
  {
    id: 'E',
    label: 'Dia E',
    name: 'Perna II — Posterior + Glúteo',
    dayOfWeek: 5,
    isRest: false,
    warmup: [
      { text: 'Ponte glútea sem peso: 2x15' },
      { text: 'RDL com bastão ou cabo leve: 10x' },
      { text: 'World greatest stretch: 5x cada lado' },
      { text: '1 série RDL com 40% do peso: 8 reps' },
    ],
    exercises: [
      { id: 'E1', name: 'Terra Romeno RDL', series: '4x10', rest: '90-120s', initialWeight: '30-40kg total' },
      { id: 'E2', name: 'Flexora de Joelho Leg Curl', series: '4x12', rest: '60-90s', initialWeight: '15-20kg' },
      { id: 'E3', name: 'Agachamento Sumo com Halter', series: '3x12', rest: '90s', initialWeight: '12-16kg halter' },
      { id: 'E4', name: 'Hip Thrust com Barra', series: '4x12', rest: '90s', initialWeight: '30-40kg total' },
      { id: 'E5', name: 'Panturrilha Sentado Sóleo', series: '4x20', rest: '60s', initialWeight: '10-15kg' },
    ],
  },
  {
    id: 'REST_SAT',
    label: 'Descanso',
    name: 'Dia de Descanso',
    dayOfWeek: 6,
    isRest: true,
    warmup: [],
    exercises: [],
  },
];

export const WEEK_PLAN = [
  { day: 'Dom', workout: 'C', name: 'Perna I', color: 'emerald' },
  { day: 'Seg', workout: 'A', name: 'Peito + Tri', color: 'blue' },
  { day: 'Ter', workout: null, name: 'Descanso', color: 'zinc' },
  { day: 'Qua', workout: 'B', name: 'Costas + Bi', color: 'purple' },
  { day: 'Qui', workout: 'D', name: 'Ombro', color: 'orange' },
  { day: 'Sex', workout: 'E', name: 'Perna II', color: 'red' },
  { day: 'Sáb', workout: null, name: 'Descanso', color: 'zinc' },
];

export const INITIAL_MEASUREMENTS = {
  date: '2026-05-10',
  ombro: 111,
  peito: 89,
  gluteo: 89,
  abdomen: 78,
  cintura: 72,
  bicepeD: 29,
  bicepeE: 30,
  antebracoD: 22,
  antebracoE: 23,
  coxaD: 53,
  coxaE: 53,
  panturrilhaD: 36,
  panturrilhaE: 36,
};

export const INITIAL_BIO = {
  date: '2026-05-11',
  peso: 61.80,
  imc: 21.6,
  gorduraCorporal: 18.6,
  musculoEsqueletico: 52.6,
  massaLivreGordura: 50.30,
  gorduraSubcutanea: 16.9,
  gorduraVisceral: 4,
  aguaCorporal: 58.8,
  massaMuscular: 47.80,
  massaOssea: 2.52,
  proteina: 18.6,
  tmb: 1456,
  idadeMetabolica: 23,
};
