export interface LibraryExercise {
  name: { pt: string; en: string };
  series: string;
  rest: string;
}

export interface MuscleGroup {
  id: string;
  icon: string;
  name: { pt: string; en: string };
  exercises: LibraryExercise[];
}

export const exerciseLibrary: MuscleGroup[] = [
  {
    id: 'peito',
    icon: '🫁',
    name: { pt: 'Peito', en: 'Chest' },
    exercises: [
      { name: { pt: 'Supino Reto com Barra', en: 'Flat Barbell Bench Press' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Supino Reto com Halteres', en: 'Flat Dumbbell Bench Press' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Supino Inclinado com Barra', en: 'Incline Barbell Bench Press' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Supino Inclinado com Halteres', en: 'Incline Dumbbell Bench Press' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Supino Declinado com Barra', en: 'Decline Barbell Bench Press' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Supino Declinado com Halteres', en: 'Decline Dumbbell Bench Press' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Crucifixo Reto', en: 'Flat Dumbbell Fly' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Crucifixo Inclinado', en: 'Incline Dumbbell Fly' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Crucifixo Declinado', en: 'Decline Dumbbell Fly' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Crossover Alto', en: 'High Cable Crossover' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Crossover Baixo', en: 'Low Cable Crossover' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Crossover Neutro', en: 'Neutral Cable Crossover' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Pullover com Halter', en: 'Dumbbell Pullover' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Pullover na Polia', en: 'Cable Pullover' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Flexão de Braço', en: 'Push-up' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Flexão Diamante', en: 'Diamond Push-up' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Flexão Inclinada', en: 'Incline Push-up' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Peck Deck / Voador', en: 'Pec Deck Fly' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Supino no Smith', en: 'Smith Machine Bench Press' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Mergulho no Banco (peito)', en: 'Chest Dip' }, series: '3x10', rest: '90s' },
    ],
  },
  {
    id: 'costas',
    icon: '🔙',
    name: { pt: 'Costas', en: 'Back' },
    exercises: [
      { name: { pt: 'Puxada Frente com Barra', en: 'Lat Pulldown' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Puxada Atrás', en: 'Behind-neck Pulldown' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Puxada Triângulo', en: 'Close-grip Pulldown' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Puxada Supinada', en: 'Reverse-grip Pulldown' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Barra Fixa Pronada', en: 'Overhand Pull-up' }, series: '3x8', rest: '90s' },
      { name: { pt: 'Barra Fixa Supinada', en: 'Chin-up' }, series: '3x8', rest: '90s' },
      { name: { pt: 'Remada Curvada com Barra', en: 'Barbell Bent-over Row' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Remada Curvada com Halteres', en: 'Dumbbell Bent-over Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Remada Unilateral com Halter', en: 'Single-arm Dumbbell Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Remada Cavalinho', en: 'T-bar Row' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Remada Sentado no Cabo', en: 'Seated Cable Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Remada Triângulo no Cabo', en: 'Close-grip Seated Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Remada no Smith', en: 'Smith Machine Row' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Levantamento Terra', en: 'Deadlift' }, series: '4x6', rest: '120s' },
      { name: { pt: 'Levantamento Terra Romeno', en: 'Romanian Deadlift' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Levantamento Terra Sumo', en: 'Sumo Deadlift' }, series: '4x6', rest: '120s' },
      { name: { pt: 'Good Morning', en: 'Good Morning' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Hiperextensão', en: 'Back Extension' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Puxada no Cabo Reto', en: 'Straight-arm Pulldown' }, series: '3x15', rest: '60s' },
    ],
  },
  {
    id: 'pernas',
    icon: '🦵',
    name: { pt: 'Pernas', en: 'Legs' },
    exercises: [
      { name: { pt: 'Agachamento Livre com Barra', en: 'Barbell Back Squat' }, series: '4x10', rest: '120s' },
      { name: { pt: 'Agachamento Frontal', en: 'Front Squat' }, series: '4x8', rest: '120s' },
      { name: { pt: 'Agachamento com Halteres', en: 'Dumbbell Squat' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Agachamento Goblet', en: 'Goblet Squat' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Agachamento no Smith', en: 'Smith Machine Squat' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Agachamento Sumô', en: 'Sumo Squat' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Agachamento Búlgaro', en: 'Bulgarian Split Squat' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Leg Press 45°', en: 'Leg Press 45°' }, series: '4x12', rest: '90s' },
      { name: { pt: 'Leg Press Horizontal', en: 'Horizontal Leg Press' }, series: '4x12', rest: '90s' },
      { name: { pt: 'Hack Squat', en: 'Hack Squat' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Cadeira Extensora', en: 'Leg Extension' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Mesa Flexora', en: 'Lying Leg Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Cadeira Flexora', en: 'Seated Leg Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Flexão de Joelho em Pé (cabo)', en: 'Standing Leg Curl' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Avanço com Barra', en: 'Barbell Lunge' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Avanço com Halteres', en: 'Dumbbell Lunge' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Avanço Reverso', en: 'Reverse Lunge' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Stiff com Barra', en: 'Stiff-leg Deadlift' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Stiff com Halteres', en: 'Dumbbell Stiff-leg Deadlift' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Passada (Caminhada)', en: 'Walking Lunge' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Panturrilha em Pé', en: 'Standing Calf Raise' }, series: '4x15', rest: '60s' },
      { name: { pt: 'Panturrilha Sentado', en: 'Seated Calf Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Panturrilha no Leg Press', en: 'Leg Press Calf Raise' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdução de Quadril (máquina)', en: 'Machine Hip Abduction' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Adução de Quadril (máquina)', en: 'Machine Hip Adduction' }, series: '3x15', rest: '60s' },
    ],
  },
  {
    id: 'gluteos',
    icon: '🍑',
    name: { pt: 'Glúteos', en: 'Glutes' },
    exercises: [
      { name: { pt: 'Hip Thrust com Barra', en: 'Barbell Hip Thrust' }, series: '4x12', rest: '90s' },
      { name: { pt: 'Hip Thrust com Halter', en: 'Dumbbell Hip Thrust' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Hip Thrust Unilateral', en: 'Single-leg Hip Thrust' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Elevação Pélvica no Chão', en: 'Glute Bridge' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Elevação Pélvica Unilateral', en: 'Single-leg Glute Bridge' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Agachamento Sumô com Barra', en: 'Sumo Barbell Squat' }, series: '4x12', rest: '90s' },
      { name: { pt: 'Coice no Cabo (extensão de quadril)', en: 'Cable Kickback' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Coice com Caneleira', en: 'Ankle Weight Kickback' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Abdução na Polia Baixa', en: 'Cable Hip Abduction' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Abdução com Elástico', en: 'Band Hip Abduction' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Agachamento Búlgaro (foco glúteo)', en: 'Glute-focused Bulgarian Split Squat' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Stiff Unilateral', en: 'Single-leg Romanian Deadlift' }, series: '3x10', rest: '60s' },
      { name: { pt: 'Monster Walk com Elástico', en: 'Monster Walk with Band' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Extensão de Quadril na Máquina', en: 'Machine Hip Extension' }, series: '3x15', rest: '60s' },
    ],
  },
  {
    id: 'ombros',
    icon: '🏈',
    name: { pt: 'Ombros', en: 'Shoulders' },
    exercises: [
      { name: { pt: 'Desenvolvimento com Barra (frente)', en: 'Military Press' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Desenvolvimento com Barra (atrás)', en: 'Behind-neck Press' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Desenvolvimento com Halteres', en: 'Dumbbell Shoulder Press' }, series: '4x12', rest: '90s' },
      { name: { pt: 'Desenvolvimento Arnold', en: 'Arnold Press' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Desenvolvimento no Smith', en: 'Smith Machine Shoulder Press' }, series: '3x12', rest: '90s' },
      { name: { pt: 'Elevação Lateral com Halteres', en: 'Dumbbell Lateral Raise' }, series: '4x15', rest: '60s' },
      { name: { pt: 'Elevação Lateral no Cabo', en: 'Cable Lateral Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Elevação Lateral com Elástico', en: 'Band Lateral Raise' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Elevação Frontal com Halter', en: 'Dumbbell Front Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Elevação Frontal com Barra', en: 'Barbell Front Raise' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Elevação Frontal no Cabo', en: 'Cable Front Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Pássaro (crucifixo inverso)', en: 'Reverse Dumbbell Fly' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Pássaro na Polia', en: 'Cable Reverse Fly' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Pássaro na Máquina', en: 'Machine Reverse Fly' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Encolhimento com Halteres', en: 'Dumbbell Shrug' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Encolhimento com Barra', en: 'Barbell Shrug' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Face Pull', en: 'Face Pull' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Upright Row com Barra', en: 'Barbell Upright Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Upright Row com Halter', en: 'Dumbbell Upright Row' }, series: '3x12', rest: '60s' },
    ],
  },
  {
    id: 'biceps',
    icon: '💪',
    name: { pt: 'Bíceps', en: 'Biceps' },
    exercises: [
      { name: { pt: 'Rosca Direta com Barra', en: 'Barbell Curl' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Rosca Direta com EZ', en: 'EZ Bar Curl' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Rosca Alternada com Halteres', en: 'Alternating Dumbbell Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca Simultânea com Halteres', en: 'Simultaneous Dumbbell Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca Martelo', en: 'Hammer Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca Martelo no Cabo', en: 'Cable Hammer Curl' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Rosca Concentrada', en: 'Concentration Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca Scott com Barra', en: 'EZ Bar Preacher Curl' }, series: '3x10', rest: '60s' },
      { name: { pt: 'Rosca Scott com Halter', en: 'Dumbbell Preacher Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca no Cabo Baixo', en: 'Low Cable Curl' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Rosca no Cabo Alto', en: 'High Cable Curl' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Rosca Inversa', en: 'Reverse Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca Inclinada com Halteres', en: 'Incline Dumbbell Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Rosca 21', en: '21s Curl' }, series: '3x21', rest: '60s' },
      { name: { pt: 'Chin-up (supinado)', en: 'Chin-up' }, series: '3x8', rest: '90s' },
    ],
  },
  {
    id: 'triceps',
    icon: '🔱',
    name: { pt: 'Tríceps', en: 'Triceps' },
    exercises: [
      { name: { pt: 'Tríceps Corda no Cabo', en: 'Cable Rope Pushdown' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Tríceps Barra no Cabo', en: 'Cable Bar Pushdown' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Tríceps Inverso no Cabo', en: 'Reverse Grip Pushdown' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Tríceps Unilateral no Cabo', en: 'Single-arm Cable Pushdown' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Tríceps Testa com Barra', en: 'Barbell Skull Crusher' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Tríceps Testa com EZ', en: 'EZ Bar Skull Crusher' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Tríceps Testa com Halteres', en: 'Dumbbell Skull Crusher' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Tríceps Francês com Barra', en: 'Barbell French Press' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Tríceps Francês com Halter', en: 'Dumbbell Overhead Tricep Extension' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Tríceps Coice com Halter', en: 'Dumbbell Kickback' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Tríceps Banco (mergulho)', en: 'Bench Dip' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Mergulho nas Paralelas', en: 'Parallel Bar Dip' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Supino Fechado (tríceps)', en: 'Close-grip Bench Press' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Tríceps no Banco Inclinado', en: 'Incline Bench Tricep Extension' }, series: '3x12', rest: '60s' },
    ],
  },
  {
    id: 'abdomen',
    icon: '🎯',
    name: { pt: 'Abdômen', en: 'Core' },
    exercises: [
      { name: { pt: 'Prancha Frontal', en: 'Plank' }, series: '3x60s', rest: '60s' },
      { name: { pt: 'Prancha Lateral', en: 'Side Plank' }, series: '3x45s', rest: '60s' },
      { name: { pt: 'Prancha com Elevação de Braço', en: 'Plank with Arm Raise' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal Crunch', en: 'Crunch' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal com Rotação', en: 'Rotational Crunch' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal Bicicleta', en: 'Bicycle Crunch' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal Infra (elevação de pernas)', en: 'Leg Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Abdominal Infra na Barra', en: 'Hanging Leg Raise' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Abdominal Infra no Cabo', en: 'Cable Leg Raise' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Russian Twist com Peso', en: 'Weighted Russian Twist' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal na Máquina', en: 'Crunch Machine' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Abdominal no Cabo (joelho)', en: 'Kneeling Cable Crunch' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Dead Bug', en: 'Dead Bug' }, series: '3x10', rest: '60s' },
      { name: { pt: 'Hollow Body Hold', en: 'Hollow Body Hold' }, series: '3x30s', rest: '60s' },
      { name: { pt: 'V-up', en: 'V-up' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Mountain Climber', en: 'Mountain Climber' }, series: '3x30', rest: '60s' },
      { name: { pt: 'Abdominal com Bola Suíça', en: 'Swiss Ball Crunch' }, series: '3x20', rest: '60s' },
      { name: { pt: 'Toe Touch', en: 'Toe Touch' }, series: '3x20', rest: '60s' },
    ],
  },
  {
    id: 'trapezio',
    icon: '🏔️',
    name: { pt: 'Trapézio', en: 'Traps' },
    exercises: [
      { name: { pt: 'Encolhimento com Barra (frente)', en: 'Barbell Shrug' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Encolhimento com Halteres', en: 'Dumbbell Shrug' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Encolhimento no Cabo', en: 'Cable Shrug' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Encolhimento com Barra Atrás', en: 'Behind-back Barbell Shrug' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Face Pull', en: 'Face Pull' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Upright Row com Barra', en: 'Barbell Upright Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Upright Row com Halteres', en: 'Dumbbell Upright Row' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Farmer Walk', en: 'Farmer Walk' }, series: '3x30s', rest: '90s' },
      { name: { pt: 'Clean de Potência', en: 'Power Clean' }, series: '4x5', rest: '120s' },
      { name: { pt: 'Remada Alta com Barra', en: 'High Pull' }, series: '3x10', rest: '90s' },
    ],
  },
  {
    id: 'lombar',
    icon: '🔴',
    name: { pt: 'Lombar', en: 'Lower Back' },
    exercises: [
      { name: { pt: 'Hiperextensão no Banco', en: 'Hyperextension' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Hiperextensão Inversa', en: 'Reverse Hyperextension' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Good Morning com Barra', en: 'Good Morning' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Superman', en: 'Superman' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Bird Dog', en: 'Bird Dog' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Levantamento Terra (lombar)', en: 'Deadlift' }, series: '4x6', rest: '120s' },
      { name: { pt: 'Levantamento Terra Romeno', en: 'Romanian Deadlift' }, series: '4x10', rest: '90s' },
      { name: { pt: 'Remada Curvada (foco lombar)', en: 'Bent-over Row' }, series: '3x10', rest: '90s' },
      { name: { pt: 'Extensão Lombar na Máquina', en: 'Machine Back Extension' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Prancha com Rotação de Quadril', en: 'Hip Rotation Plank' }, series: '3x20', rest: '60s' },
    ],
  },
  {
    id: 'antebraco',
    icon: '🦾',
    name: { pt: 'Antebraço', en: 'Forearms' },
    exercises: [
      { name: { pt: 'Rosca de Pulso com Barra (pronada)', en: 'Barbell Wrist Curl' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Rosca de Pulso com Barra (supinada)', en: 'Reverse Wrist Curl' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Rosca de Pulso com Halteres', en: 'Dumbbell Wrist Curl' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Rosca Inversa (antebraço)', en: 'Reverse Curl' }, series: '3x15', rest: '60s' },
      { name: { pt: 'Farmer Walk', en: 'Farmer Walk' }, series: '3x30s', rest: '90s' },
      { name: { pt: 'Dead Hang na Barra', en: 'Dead Hang' }, series: '3x30s', rest: '60s' },
      { name: { pt: 'Squeeze de Borracha / Expansor', en: 'Grip Squeeze' }, series: '3x20', rest: '45s' },
      { name: { pt: 'Rolar o Pulso com Halter', en: 'Wrist Roller' }, series: '3x5', rest: '60s' },
      { name: { pt: 'Rosca Martelo (antebraço)', en: 'Hammer Curl' }, series: '3x12', rest: '60s' },
      { name: { pt: 'Pronação e Supinação com Halter', en: 'Wrist Pronation/Supination' }, series: '3x15', rest: '45s' },
    ],
  },
  {
    id: 'cardio',
    icon: '🏃',
    name: { pt: 'Cardio / HIIT', en: 'Cardio / HIIT' },
    exercises: [
      { name: { pt: 'Esteira (corrida)', en: 'Treadmill Run' }, series: '1x30min', rest: '—' },
      { name: { pt: 'Esteira (caminhada inclinada)', en: 'Incline Treadmill Walk' }, series: '1x30min', rest: '—' },
      { name: { pt: 'Bicicleta Ergométrica', en: 'Stationary Bike' }, series: '1x30min', rest: '—' },
      { name: { pt: 'Elíptico', en: 'Elliptical' }, series: '1x30min', rest: '—' },
      { name: { pt: 'Rowing (remo ergômetro)', en: 'Rowing Machine' }, series: '1x20min', rest: '—' },
      { name: { pt: 'Pular Corda', en: 'Jump Rope' }, series: '5x2min', rest: '60s' },
      { name: { pt: 'Burpee', en: 'Burpee' }, series: '4x10', rest: '60s' },
      { name: { pt: 'Jumping Jack', en: 'Jumping Jack' }, series: '3x30', rest: '45s' },
      { name: { pt: 'Mountain Climber', en: 'Mountain Climber' }, series: '4x30', rest: '60s' },
      { name: { pt: 'Sprint na Esteira (HIIT)', en: 'Treadmill Sprint (HIIT)' }, series: '8x30s', rest: '30s' },
      { name: { pt: 'Bike Sprint (HIIT)', en: 'Bike Sprint (HIIT)' }, series: '8x30s', rest: '30s' },
      { name: { pt: 'Box Jump', en: 'Box Jump' }, series: '4x10', rest: '60s' },
      { name: { pt: 'Kettlebell Swing', en: 'Kettlebell Swing' }, series: '4x15', rest: '60s' },
      { name: { pt: 'Agachamento com Salto', en: 'Jump Squat' }, series: '4x12', rest: '60s' },
      { name: { pt: 'Battle Rope', en: 'Battle Rope' }, series: '5x30s', rest: '60s' },
    ],
  },
];
